version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/index.html:/www/index.html
