version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      # - wordpress-volume:/var/www/html
      - ./data/wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - server
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      # - wordpress-volume:/var/www/html
      - ./data/wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - server
      - database
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      # - mariadb-volume:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
    networks:
      - database
    restart: always
    healthcheck:
      test: mariadb -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e use ${MYSQL_DATABASE}
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s

volumes:
  mariadb-volume:
    driver_opts:
      type: none
      device: ./data/mysql
      o: bind
  wordpress-volume:
    driver_opts:
      type: none
      device: ./data/wordpress
      o: bind

networks:
  server:
    driver: bridge
  database:
    driver: bridge
