version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/src:/var/www/html
    depends_on:
      - wordpress
    networks:
      - server
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - ./requirements/src:/var/www/html
    # - server-volume:/var/www/html
    networks:
      - server
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    # restart: always

volumes:
  server-volume:
    driver_opts:
      type: none
      device: ./requirements/wordpress/src
      o: bind

networks:
  server:
    driver: bridge
