version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/html
    depends_on:
      - wordpress
      - adminer
    networks:
      - server
      - manage-mysql
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress-volume:/var/www/html
    env_file:
      - .env
    depends_on:
      - redis
      - mariadb
      # mariadb:
      #   condition: service_healthy
    networks:
      - server
      - database
      - cache
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - database
      - manage-mysql
    restart: always
    # healthcheck:
    #   test: mariadb -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e use ${MYSQL_DATABASE}
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  redis:
    image: redis
    container_name: redis
    build: requirements/redis
    volumes:
      - redis-volume:/data
    networks:
      - cache
    env_file:
      - .env
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    build: requirements/adminer
    networks:
      - manage-mysql
    # ports:
    #   - "8300:8300"

volumes:
  mariadb-volume:
    driver_opts:
      type: none
      o: bind
      device: "${DATA_PATH}/mysql"
  wordpress-volume:
    driver_opts:
      type: none
      o: bind
      device: "${DATA_PATH}/wordpress"
  redis-volume:
    driver_opts:
      type: none
      o: bind
      device: "${DATA_PATH}/redis"

networks:
  server:
    driver: bridge
  database:
    driver: bridge
  cache:
    driver: bridge
  manage-mysql:
    driver: bridge
