FROM alpine:3.15

RUN apk add --no-cache --update tini mosquitto mosquitto-libs mosquitto-clients

COPY mosquitto.conf /tmp/mosquitto.conf
RUN chmod 777 /tmp/mosquitto.conf

ENTRYPOINT ["tini", "-vv", "--"]
CMD [ "mosquitto", "-c", "/tmp/mosquitto.conf", "-v" ]
