FROM alpine:3.15

RUN apk add --no-cache --update tini mosquitto mosquitto-libs mosquitto-clients

COPY mosquitto.conf /etc/mosquitto/

ENTRYPOINT ["tini", "-vv", "--"]
# CMD [ "tail", "-f" ]
CMD [ "mosquitto" ]
